project:
  type: website
  output-dir: docs

website:
  title: "Isabelle Li - MUSA 5080 Portfolio"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - text: "Weekly Notes" 
        menu:
          - href: weekly-notes/
            text: "All Notes"
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1 Notes"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2 Notes"
          - href: weekly-notes/week-03-notes.qmd
            text: "Week 3 Notes"
          - href: weekly-notes/week-04-notes.qmd
            text: "Week 4 Notes"
            
            

      - text: "labs"
        menu:
          - href: labs/
            text: "All labs"
          - href: labs/lab_0/scripts/lab0_template.qmd
            text: "lab 0"
          - href: labs/lab_1/week-03/scrips/week3_lab_exercise.qmd
            text: "lab 1"
            
      - text: "assignments"
        menu:
          - href: assignments/
            text: "All assignments"
          - href: assignments/assignment1/assignment1_template.qmd
            text: "assignment1"


format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
