project:
  type: website
  output-dir: docs

website:
  title: "Isabelle Li - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Weekly Notes"
        menu:
          - href: weekly-notes/
            text: "All Notes"
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2"
      - text: "Labs"
        menu:
          - href: Labs/
            text: "All Labs"
          - href: Labs/lab_0/scripts/lab0_template.qmd
            text: "Lab 0"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
